FROM node:18

# Set the working directory
WORKDIR /app

# Copy only package.json and package-lock.json first
COPY ./frontend/package*.json ./

# Remove node_modules and package-lock.json if they exist, and install dependencies
RUN rm -rf node_modules package-lock.json && npm install --legacy-peer-deps

# Copy the rest of the app
COPY ./frontend ./

# Expose the frontend port
EXPOSE 5173

# Start the Vite development server
CMD ["npm", "run", "dev", "--", "--host"]